language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
after_success:
  - npm run semantic-release
  - npm run test:cover:upload
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
